# Generated by Django 4.1.5 on 2023-11-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_punch_image'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='punch',
            order_with_respect_to=None,
        ),
    ]
