# Generated by Django 4.1.5 on 2023-11-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_punch_order_with_respect_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punch',
            name='image',
        ),
        migrations.CreateModel(
            name='PunchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='punch_images/')),
                ('punch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punchimages', to='base.punch')),
            ],
        ),
        migrations.AddField(
            model_name='punch',
            name='images',
            field=models.ManyToManyField(related_name='punchImages', to='base.punchimage'),
        ),
    ]
